version: '3.8'

services:
   mysql:
    image: mysql:5.7
    container_name: mysql-container_name
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: myapp_db
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mypass123
    ports:
      - "3306:3306"
    volumes:
      -  ./mysql_data:/var/lib/mysql    
  